name: "Close PR"

on:
  pull_request:
    types: [closed]
jobs:
  DestroyQA:
    name: 'Destroy QA Environment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set TF Azure Variables
        run: |
          export ARM_CLIENT_ID="${{ secrets.ARM_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.ARM_CLIENT_SECRET }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.ARM_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ secrets.ARM_TENANT_ID }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Select TF Workspace
        run: |
          terraform workspace select azure-master-plan-${{ github.head_ref }}

      - name: Destroy preview environment
        if: github.event.action == 'closed'
        id: destroy-preview-environment
        run: terraform destroy -auto-approve
        continue-on-error: true
