name: "Close PR"

on:
  pull_request:
    types: [closed]
env:
  workspace:  "azure-master-plan-BRANCH-${{ github.head_ref }}"
jobs:
  DestroyQA:
    name: 'Destroy QA Environment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
      - name: set default workspace
        run: |
          rm -rf .terraform
          mkdir .terraform
          printf '%s' azure-master-plan-DEV > .terraform/environment

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Select TF Workspace
        run: terraform workspace select ${{ env.workspace }}

      - name: Destroy preview environment
        if: github.event.action == 'closed'
        id: destroy-preview-environment
        run: terraform destroy -auto-approve  -var "env=BRANCH-${{ github.head_ref }}" -var "client_id=${{ secrets.ARM_CLIENT_ID }}" -var "client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.ARM_TENANT_ID }}"
        continue-on-error: true
      
      - name: Delete TF Workspace
        run: terraform workspace delete ${{ env.workspace }}