name: "Close PR"

on:
  pull_request:
    types: [closed]

DestroyQA:
  name: 'Destroy QA Environment'
  needs: StaticTests
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Destroy preview environment
      if: github.event.action == 'closed'
      id: destroy-preview-environment
      run: terraform destroy -auto-approve
      continue-on-error: true
